version: 1 # opcional, para controle de versão do formato do arquivo
  
source: <url_or_dsl>
        | {
          value: <url_or_dsl>,
          ext?: <string>, # opcional, extensão para filtrar fontes
          tags?: <list<string>> # opcional, para filtrar fontes
        }

on?:
  
  event: 
    # herda todos os campos do modelo `id` de `scripts`

    # fase/evento que disparou a execução do script.
    #
    # - 'preresolvecanonical': antes de iniciar o processo de resolução canônica, para preparar o ambiente, validar condições, etc
    # - 'posresolvecanonical': antes de iniciar o processo de resolução canônica, para preparar o ambiente, validar condições, etc
    # - 'preresolvefinalpath': antes de resolver o caminho final, para ações de limpeza, validação, etc
    # - 'posresolvefinalpath': após resolver o caminho final, para ações de limpeza, validação, etc
    # - 'preresolveurl': antes de resolver a url, para preparar o ambiente, validar condições, etc
    # - 'posresolveurl': após resolver a url, para ações de limpeza, valida
    # - 'premetacheck': antes de iniciar o processo de identificação do arquivo a ser verificadobaixado, para preparar o ambiente, validar condições, etc
    #     * parametros fornecidos para o script:
    #       - `asline`, `matchline`, `containerpath`    
    # - 'premetagen': antes de iniciar a metageração, para configurar parâmetros, validar o ambiente, etc
    #       - `asline`, `matchline`, `containerpath`, as, match, internalpath, finalpath
    # - 'posmetagen': antes de iniciar a metageração, para configurar parâmetros, validar o ambiente, etc
    #       - `asline`, `matchline`, `containerpath`, as, match, internalpath, finalpath    
    <string> # fase em que o evento deve ser disparado                      
      
naming:
  final: <string>
  canonical: <string>

integrity?:
  # integridade: se for string, é interpretada como `remote`.
  # NOTA: Refere-se ao hash do arquivo baixado e não deve ser interpretada como  
  # conferência obrigatória do arquivo existente na origem ou destino. Em casos
  # de extração, o hash do arquivo final pode diferir do hash do arquivo
  # baixado (ex: containers compactados). O script deve associar o valor do
  # campo `integrity` ao arquivo correto — seja ele o baixado ou o final,
  # conforme o contexto da fase — e correlacionar o hash adequado dos arquivos
  # finais baseando-se no valor do arquivo .sha256 e de .syncado equivalente.
  <string> 
  | {
  fixed?: <string|null> # hash literal (md5|sha1|sha256|...)
  remote?: <string|null> # url | dsl | hash literal
    |{
      value: <string> # obrigatório se objeto
      type?:
        # default auto - inferida pelo tamanho da string ou
        # prefixo, ou pela extensão do arquivo, etc                         
        "auto" | "sha256" | "sha1" | "md5"
      }
  }

container?:  
  - match: '.+\.iso' # regex match para arquivos a serem extraídos
    as: 'ubuntu.iso' # nome destino para o arquivo extraído, pode usar
                      # $1, $2, etc para referenciar grupos de captura
                      # da regex, incluindo grupos nomeados, por exemplo,
                      # (?P<name>pattern)

    on?: # Segue o modelo especificado dentro do campo `on` do root. Mas
        # é específico para o início o processo de extração do arquivo           
        # que corresponde ao match, ou seja, pode ser diferente para
        # cada arquivo a ser extraído, por exemplo, para calcular um hash
        # específico para cada arquivo, etc. Herda os demais parâmetros
        # do modelo especificado dentro do campo `on` do root.

      # Além dos parâmetros padrão passados, incluídos
      # especificados na sessão `scripts`, os desta sessão, podem incluir:
      # - containerpath : o full path do arquivo container
      # - as: o nome resolvine destino para o arquivo extraído, conforme
      #   definido no campo `as` - se já resolvido
      # - match: o regex match (resolvido) que acionou a extração, por exemplo,
      #   '.+\.iso' - se já resolvido
      # - internalpath: o caminho interno do arquivo dentro do
      #   container, se já resolvido, por exemplo, 'ubuntu.iso' ou 'path/to/ubuntu.iso'
      # - asline: o campo `line` extamente como está na linha, ou seja, sem resolução de variáveis ou regex, etc
      # - matchline: o campo `match` extamente como está na linha, ou seja, sem resolução de variáveis ou regex, etc
      #   '.+\.iso' - se já resolvido 
      # - finalpath: caminho completo do arquivo extraído

      - event: 
          # fase/evento que disparou o script. Para extração, 
          # eventos típicos podem ser:
          #
          # - 'premetacheck': antes de iniciar o processo de identificação do arquivo a ser extraído, para preparar o ambiente, validar condições, etc
          #     * parametros fornecidos para o script:
          #       - `asline`, `matchline`, `containerpath`
          # - 'prematch': antes de fazer o match, para preparar o ambiente, validar condições, etc
          #     * parametros fornecidos para o script:
          #       - `asline`, `matchline`, `containerpath`
          # - 'postmatch': após o match, para realizar ações específicas com base no arquivo identificado, como calcular hashes, mover arquivos, etc
          #     * parametros fornecidos para o script:
          #       - `asline`, `matchline`, `containerpath`, as, match, internalpath
          # - 'preextract': antes de iniciar a extração, para configurar parâmetros, validar o ambiente, etc
          #     * parametros fornecidos para o script:
          #       - `asline`, `matchline`, `containerpath`, as, match, internalpath            
          # - 'postextract': após a extração, para ações de limpeza, validação, etc 
          #     * parametros fornecidos para o script:
          #       - `asline`, `matchline`, `containerpath`, as, match, internalpath, finalpath
          # - 'premetagen': antes de iniciar a metageração, para configurar parâmetros, validar o ambiente, etc
          #       - `asline`, `matchline`, `containerpath`, as, match, internalpath, finalpath
          # - 'posmetagen': antes de iniciar a metageração, para configurar parâmetros, validar o ambiente, etc
          #       - `asline`, `matchline`, `containerpath`, as, match, internalpath, finalpath
          <string>          

scripts?:
  # Todo script irá receber parâmetros nomeados (adequado ao ambiente
  # e linguagem), ao ser executado, por exemplo:
  # `./script13.sh --syncdownload "<url_or_dsl>" --value <value>
  # --as "<as>"`

  # Os parâmetros nomeados disponíveis para o script de extração,
  # além de outros contextuais, podem incluir:
  # - syncdownload: o full path do arquivo syncdownload.yaml, para
  #   casos em que o script precise ler ou modificar o arquivo de
  #   configuração    
  # - eventname: o nome do evento chamador, como posresolve, 
  #   preinstall, etc
  # - parâmetros específicos do evento chamador  

  # O script pode retornar algo que substitua variáveis de ambiente ou
  # parâmetros para etapas subsequentes, por exemplo, o caminho do
  # arquivo extraído, ou um hash calculado, etc, incluindo os campos
  # `match` e `as`. O script deve prever e separar a saída real de
  # mensagens de log, warn ou erros, por exemplo, usando um formato
  # específico ou delimitadores.

  - id: <string|null> # identificador único global para
                  # identificar o script em invocações, logs, etc
    lang: <string|null> # opcional se run for um path/base64 (base64 
                        # contem extensão embudida na definição),
                        # caso contrário, obrigatório - linguagem do
                        # comando de extração (sh, bat, py, etc)

    run:
      # Pode ser:
      # - string única
      # - lista plana de strings
      #
      # Cada string pode ser:
      # 1. Referência a script:
      #    - DEVE iniciar com ":"
      #    - formato: ":<id>"
      #
      # 2. Caminho relativo ou comando inline:
      #    - qualquer string que NÃO inicie com ":"
      #
      # 3. Código inline multilinha:
      #    - permitido quando a string contiver múltiplas linhas
      #    - pode ser definido:
      #        a) diretamente no formato YAML (ex: | ou >) ou adequado à linguagem
      #        b) como conteúdo codificado em base64, usando o prefixo:
      #           "data:;base64,<conteúdo>"
      #
      # Regras:
      # - ":" só tem significado especial quando no INÍCIO da string
      # - referências são resolvidas e expandidas (flatten)
      # - listas devem ser planas (sem aninhamento)
      # - ordem de execução deve ser preservada
      # - conteúdo com prefixo "data:;base64," deve ser decodificado antes
      #   da execução
      <string>
      | <list<string>>